### ISSUE TITLE
DM ONE

### ISSUE THREAD

**Issue by EnoSat** [fairbird/RaedQuickSignal#37] opened 2024-03-25 18:56 UTC
DreamboxOS 5.0.0r0-11-g416f6-2023-04-24
after install not show in plugins
[dmONE.log](https://github.com/fairbird/RaedQuickSignal/files/14748314/dmONE.log)

**Comment by EnoSat** [comment] 2024-03-26 11:31
![DMONE2](https://github.com/fairbird/RaedQuickSignal/assets/4271667/eeb53e9c-0486-437b-a697-cbc2719103b9)
![DMONE1](https://github.com/fairbird/RaedQuickSignal/assets/4271667/43818741-02a9-46e6-8bef-254ddf556935)

**Comment by fairbird** [comment] 2024-03-26 11:35
As I said I can not help you without e2 log .. How can I figure out the problem with screenshots ?!

**Comment by EnoSat** [comment] 2024-03-26 13:18
ahha, log, not logo
> must send me the Enigma logo
[dmONE.log](https://github.com/fairbird/RaedQuickSignal/files/14758919/dmONE.log)

**Comment by fairbird** [comment] 2024-03-26 17:46
The log does not appear any thing about RaedQuickSignal ..
So ... first please give this command in telnet and look if plugin install or not 
> ls /usr/lib/enigma2/python/Plugins/Extensions/RaedQuickSignal

If you found RaedQuickSignal plugin then open plugin browser with enable e2 debuge and send the e2 log again.

**Comment by fairbird** [comment] 2024-04-01 19:20
You did not answered me in this issue ?
Did you test other image ?! if you then please close this issue !

**Comment by EnoSat** [comment] 2024-04-01 21:34
Unless the plugin is installed in OE2.6, I have nothing to test :(

**Comment by fairbird** [comment] 2024-04-01 22:28
What image you have tested ?!!
Did you tested Merlin or newnigma2 ?!

**Comment by EnoSat** [comment] 2024-04-02 17:18
GP

**Comment by fairbird** [comment] 2024-04-03 11:29
Already I have prove it to you in this replay no problem on GP
https://github.com/fairbird/RaedQuickSignal/issues/37#issuecomment-2019034650

And I asked you also to test other image. Don't just rely on one picture that might be the problem ؟!

**Comment by EnoSat** [comment] 2024-04-03 14:35
DM920 uses OE2.5 v4.3 (32b), DMone uses OE2.6 v5.0 (64b)
As you saw in the first log, the installation was successful, but the plugin does not appear in Plugins

**Comment by fairbird** [comment] 2024-04-03 22:09
Again and Again and Again ... I will repeat my last replay ...
PLEASE DON"T RELY ON ONE IMAGE ... SO PLEASE TEST OTHER IMAGES SUCH AS (Merlin or newnigma2)

And I AGAIN I WIll prove to you NO problem on GP4 image as you see I have download and install New fresh image + install plugin ... Look to screenshots (Plugin appear and works after install or not ?!!!) 
> The Gemini Project 4.2 
.
dm920 login: root
root@dm920:~# apt install wget
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following NEW packages will be installed:
  wget
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 169 kB of archives.
After this operation, 0 B of additional disk space will be used.
Get:1 http://download.blue-panel.com/opendreambox/2.5/unstable/r0/dm920/deb/cortexa15hf-neon-vfpv4/ ./ wget 1.17.1-r0.4 [169 kB]
Fetched 169 kB in 0s (289 kB/s)
Selecting previously unselected package wget.
(Reading database ... 15508 files and directories currently installed.)
Preparing to unpack .../wget_1.17.1-r0.4_armhf.deb ...
Unpacking wget (1.17.1-r0.4) ...
Setting up wget (1.17.1-r0.4) ...
update-alternatives: using /usr/bin/wget.wget to provide /usr/bin/wget (wget) in auto mode
root@dm920:~# wget "--no-check-certificate" https://raw.githubusercontent.com/fairbird/RaedQuickSignal/main/installer.sh -O - | /bin/sh
--2024-04-04 01:02:03--  https://raw.githubusercontent.com/fairbird/RaedQuickSignal/main/installer.sh
Resolving raw.githubusercontent.com... 2606:50c0:8002::154, 2606:50c0:8001::154, 2606:50c0:8000::154, ...
Connecting to raw.githubusercontent.com|2606:50c0:8002::154|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 6800 (6.6K) [text/plain]
Saving to: 'STDOUT'
.
2024-04-04 01:02:03 (3.00 MB/s) - written to stdout [6800/6800]
.
You have Python2 image
.
Your image is OE2.5/2.6
.
--2024-04-04 01:02:03--  https://github.com/fairbird/RaedQuickSignal/archive/refs/heads/main.tar.gz
Resolving github.com... 20.233.83.145
Connecting to github.com|20.233.83.145|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://codeload.github.com/fairbird/RaedQuickSignal/tar.gz/refs/heads/main [following]
--2024-04-04 01:02:04--  https://codeload.github.com/fairbird/RaedQuickSignal/tar.gz/refs/heads/main
Resolving codeload.github.com... 20.233.83.150
Connecting to codeload.github.com|20.233.83.150|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [application/x-gzip]
Saving to: 'main.tar.gz'
.
main.tar.gz                                     [              <=>                                                                           ]  29.06M  11.0MB/s    in 2.6s    
.
2024-04-04 01:02:07 (11.0 MB/s) - 'main.tar.gz' saved [30469984]
.
--2024-04-04 01:02:08--  https://github.com/fairbird/RaedQuickSignal/raw/main/RaedQuickServName2-dreamos.tar.gz
Resolving github.com... 20.233.83.145
Connecting to github.com|20.233.83.145|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://raw.githubusercontent.com/fairbird/RaedQuickSignal/main/RaedQuickServName2-dreamos.tar.gz [following]
--2024-04-04 01:02:08--  https://raw.githubusercontent.com/fairbird/RaedQuickSignal/main/RaedQuickServName2-dreamos.tar.gz
Resolving raw.githubusercontent.com... 2606:50c0:8002::154, 2606:50c0:8001::154, 2606:50c0:8000::154, ...
Connecting to raw.githubusercontent.com|2606:50c0:8002::154|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 6049 (5.9K) [application/octet-stream]
Saving to: 'RaedQuickServName2-dreamos.tar.gz'
.
RaedQuickServName2-dreamos.tar.gz           100%[===========================================================================================>]   5.91K  --.-KB/s    in 0s      
.
2024-04-04 01:02:09 (11.9 MB/s) - 'RaedQuickServName2-dreamos.tar.gz' saved [6049/6049]
.
Missing emu folder will be send it to plugin path
Missing piconProv folder will be send it to plugin path
Missing piconSat folder will be send it to plugin path
Missing piconCrypt folder will be send it to plugin path
Missing weather folder will be send it to plugin path

![1](https://github.com/fairbird/RaedQuickSignal/assets/1761779/0471c0b8-bd48-44c7-bc33-9bf756ddceb1)
![2](https://github.com/fairbird/RaedQuickSignal/assets/1761779/7013ec1b-ad67-401c-b6af-66a4c6b1bc5b)
![3](https://github.com/fairbird/RaedQuickSignal/assets/1761779/118a9edc-a7ed-455f-b369-a8db1c86d543)
![4](https://github.com/fairbird/RaedQuickSignal/assets/1761779/8061dce8-0eff-40ec-8a73-170dbc08ec47)
![5](https://github.com/fairbird/RaedQuickSignal/assets/1761779/4b399b5f-a901-4cf2-bfe8-96608f59d868)

So Again Please test other image do not test only one image and then you say there is problem in plugin ?!!
Also here in this replay You did not given me what I asked you ?!
https://github.com/fairbird/RaedQuickSignal/issues/37#issuecomment-2021094528

**Comment by EnoSat** [comment] 2024-04-04 15:06
Result:
Merlin OE2.6 DreamOS 4.5.1 - Unable to assign MAC to IP address - unusable
![capture_001_04042024_162025](https://github.com/fairbird/RaedQuickSignal/assets/4271667/cae43301-ad3a-4c8c-b515-a5b6fb9e1926)
![Melin26_45](https://github.com/fairbird/RaedQuickSignal/assets/4271667/c04bd1da-2e1d-4679-bd28-0540d0f88278)
NN2 OE2.6 DreamOS 4.5.1 - OK
![NN2_OE26_45](https://github.com/fairbird/RaedQuickSignal/assets/4271667/d854bf75-6c13-41d4-988c-e2b5b2376473)
GP42 OE2.6 DreamOS 4.5.1 - OK
![GP42screenshot](https://github.com/fairbird/RaedQuickSignal/assets/4271667/a90446b3-ca48-4ad8-939c-c186596d8a8d)
![GP42_45](https://github.com/fairbird/RaedQuickSignal/assets/4271667/0ae9bed2-e06b-4550-a0db-09bbfbc675e1)
GP42 OE2.6 DreamOS 5.0.0 - OK (after reinstallation - maybe something was in conflict, I don't know yet because now there is nothing except RQS)
![GP42_50screenshot](https://github.com/fairbird/RaedQuickSignal/assets/4271667/8ab0e5ac-386c-41ca-8ded-13aadee1c3b8)
![GP42_50](https://github.com/fairbird/RaedQuickSignal/assets/4271667/f9a9e445-b34b-4265-a735-c19a796e91c8)

**Comment by fairbird** [comment] 2024-04-04 21:53
Excellent my friend !!
So If you discover for yourself that the problem is with the image you were using, right?!!
If the problem is resolved please close the issue !

Thank you !

**Closed** 2024-04-05 19:39 UTC
